services:
  # Database
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yamine
      MYSQL_DATABASE: meuble
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
    networks:
      - mysql-phpmyadmin

  meuble:
    container_name: meuble
    image: meuble
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      - db
    restart: always
    networks:
      - mysql-phpmyadmin



networks:
  mysql-phpmyadmin:

volumes:
  db_data:


# docker-compose up -d
# http://localhost:8090

# docker-compose down