name: docker.yml
on:
    push:
    workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - name: checkout code
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t $USERNAME/actionimage .
      - name: push dockerhub
        run: docker push $USERNAME/actionimage

